services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true


    disk:
      name: n8n-data
      mountPath: /opt/render/n8n
      sizeGB: 1

    buildCommand: ""
    startCommand: "n8n start --userFolder=/opt/render/n8n"

