services:
  - type: web
    name: n8n
    env: docker
    plan: starter     # puedes probar con free, pero starter es más estable
    autoDeploy: true

    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1

    buildCommand: ""
    startCommand: "n8n start"
