services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    autoDeploy: true

    envVars:
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n

    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1

    buildCommand: ""
    startCommand: "n8n start"

